[project]
name = "odiseamvp"

[languages.python]
# Asegúrate de que la ruta al directorio backend sea correcta
path = "backend"
version = "3.11"

[languages.nodejs]
# Asegúrate de que la ruta al directorio frontend sea correcta
path = "frontend"
version = "18.x"

[phases.install]
commands = [
  # Instala todas las dependencias de Python, incluido uvicorn
  "cd backend && pip install -r requirements.txt",
  # Instala las dependencias de Node.js
  "cd frontend && npm ci"
]

[phases.build]
commands = [
  "cd frontend && npm run build"
]

[phases.start]
commands = [
  # Ejecuta uvicorn directamente, asumiendo que está instalado
  # La ruta backend.main:app se usa si tu archivo principal es main.py
  # y la instancia de FastAPI se llama app.
  # Si tu archivo principal es diferente, ajústalo.
  "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
]
