"""Initial migration

Revision ID: 1ea529dbc1e6
Revises: 
Create Date: 2024-11-30 10:50:23.798799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ea529dbc1e6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('spatial_ref_sys')
    op.alter_column('analisis', 'parcela_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_analisis_id'), 'analisis', ['id'], unique=False)
    op.create_index(op.f('ix_clima_id'), 'clima', ['id'], unique=False)
    op.alter_column('historico_rendimiento', 'parcela_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_historico_rendimiento_id'), 'historico_rendimiento', ['id'], unique=False)
    op.alter_column('parcelas', 'area',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.create_index('idx_parcelas_geom', 'parcelas', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_parcelas_id'), 'parcelas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parcelas_id'), table_name='parcelas')
    op.drop_index('idx_parcelas_geom', table_name='parcelas', postgresql_using='gist')
    op.alter_column('parcelas', 'area',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.drop_index(op.f('ix_historico_rendimiento_id'), table_name='historico_rendimiento')
    op.alter_column('historico_rendimiento', 'parcela_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_clima_id'), table_name='clima')
    op.drop_index(op.f('ix_analisis_id'), table_name='analisis')
    op.alter_column('analisis', 'parcela_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
