"""init

Revision ID: b0040951e96e
Revises: 1ea529dbc1e6
Create Date: 2025-02-04 13:14:44.092577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = 'b0040951e96e'
down_revision: Union[str, None] = '1ea529dbc1e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_clima_id', table_name='clima')
    op.drop_table('clima')
    op.drop_index('ix_historico_rendimiento_id', table_name='historico_rendimiento')
    op.drop_table('historico_rendimiento')
    op.drop_index('ix_analisis_id', table_name='analisis')
    op.drop_table('analisis')
    op.alter_column('parcelas', 'nombre',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('parcelas', 'geom',
               existing_type=Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True),
               type_=Geometry(geometry_type='POLYGON', from_text='ST_GeomFromEWKT', name='geometry'),
               nullable=True)
    op.alter_column('parcelas', 'area',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=False)
    op.create_index(op.f('ix_parcelas_nombre'), 'parcelas', ['nombre'], unique=False)
    op.drop_column('parcelas', 'cultivo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parcelas', sa.Column('cultivo', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_parcelas_nombre'), table_name='parcelas')
    op.alter_column('parcelas', 'area',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('parcelas', 'geom',
               existing_type=Geometry(geometry_type='POLYGON', from_text='ST_GeomFromEWKT', name='geometry'),
               type_=Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True),
               nullable=False)
    op.alter_column('parcelas', 'nombre',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_table('analisis',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('parcela_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('nitrogeno', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('fosforo', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('potasio', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcelas.id'], name='analisis_parcela_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='analisis_pkey')
    )
    op.create_index('ix_analisis_id', 'analisis', ['id'], unique=False)
    op.create_table('historico_rendimiento',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ano', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('parcela_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('kilos', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('calidad', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('comentario', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcelas.id'], name='historico_rendimiento_parcela_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='historico_rendimiento_pkey')
    )
    op.create_index('ix_historico_rendimiento_id', 'historico_rendimiento', ['id'], unique=False)
    op.create_table('clima',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('region', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('temperatura', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('precipitacion', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('viento', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='clima_pkey')
    )
    op.create_index('ix_clima_id', 'clima', ['id'], unique=False)
    # ### end Alembic commands ###
