"""ERROR TASKLIST

Revision ID: 04254f5bbd14
Revises: 1927924137fd
Create Date: 2025-08-29 12:26:28.239688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '04254f5bbd14'
down_revision: Union[str, None] = '1927924137fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_list_task_key', table_name='task_list')
    op.create_index(op.f('ix_task_list_task_list_id'), 'task_list', ['task_list_id'], unique=False)
    op.create_unique_constraint(None, 'task_list', ['task_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_list', type_='unique')
    op.drop_index(op.f('ix_task_list_task_list_id'), table_name='task_list')
    op.create_index('ix_task_list_task_key', 'task_list', ['task_key'], unique=True)
    # ### end Alembic commands ###
