"""CREAR Tablas finca y sector

Revision ID: 1130fe666587
Revises: e9459c29b6c3
Create Date: 2025-08-29 13:57:40.702783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '1130fe666587'
down_revision: Union[str, None] = 'e9459c29b6c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_index(op.f('ix_finca_id'), 'finca', ['id'], unique=False)
    op.create_table('sectores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finca_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['finca_id'], ['finca.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sectores_id'), 'sectores', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sectores_id'), table_name='sectores')
    op.drop_table('sectores')
    op.drop_index(op.f('ix_finca_id'), table_name='finca')
    op.drop_table('finca')
    # ### end Alembic commands ###
