"""OPERACIONES

Revision ID: 1ba2b4b86f08
Revises: 6d1c2b1cd2fa
Create Date: 2025-09-05 15:48:27.799019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '1ba2b4b86f08'
down_revision: Union[str, None] = '6d1c2b1cd2fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('operaciones', 'creation_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.create_index('idx_operacion_creation_date', 'operaciones', ['creation_date'], unique=False)
    op.create_index('idx_operacion_estado_fecha', 'operaciones', ['estado', 'fecha_inicio'], unique=False)
    op.create_index('idx_operacion_parcela_tipo', 'operaciones', ['parcela_id', 'tipo_operacion'], unique=False)
    op.create_index('idx_operacion_responsable', 'operaciones', ['responsable_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_operacion_responsable', table_name='operaciones')
    op.drop_index('idx_operacion_parcela_tipo', table_name='operaciones')
    op.drop_index('idx_operacion_estado_fecha', table_name='operaciones')
    op.drop_index('idx_operacion_creation_date', table_name='operaciones')
    op.alter_column('operaciones', 'creation_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_DATE'))
    # ### end Alembic commands ###
