"""prueba 1024

Revision ID: 4bb6f7d85909
Revises: 0e3ed19952cb
Create Date: 2025-08-29 08:55:07.594471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '4bb6f7d85909'
down_revision: Union[str, None] = '53dd397e9ca9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plot', sa.Column('finca', sa.String(), nullable=True))
    op.add_column('plot', sa.Column('sector', sa.String(), nullable=True))
    op.alter_column('task_list', 'task_list_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("nextval('task_list_task_list_id_seq'::regclass)"))
    op.alter_column('task_list', 'task_key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_task_list_task_list_id', table_name='task_list')
    op.create_index(op.f('ix_task_list_task_key'), 'task_list', ['task_key'], unique=True)
    op.alter_column('usuarios', 'nombre',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'nombre',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_task_list_task_key'), table_name='task_list')
    op.create_index('ix_task_list_task_list_id', 'task_list', ['task_list_id'], unique=False)
    op.alter_column('task_list', 'task_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('task_list', 'task_list_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("nextval('task_list_task_list_id_seq'::regclass)"))
    op.drop_column('plot', 'sector')
    op.drop_column('plot', 'finca')
    # ### end Alembic commands ###
