"""prueba 1012

Revision ID: 5e8809a17211
Revises: dcacf658687d
Create Date: 2025-08-28 22:00:49.092846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '5e8809a17211'
down_revision: Union[str, None] = 'dcacf658687d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('operaciones_tipo_operacion_fkey', 'operaciones', type_='foreignkey')
    op.create_foreign_key(None, 'operaciones', 'task_list', ['tipo_operacion'], ['task_key'])
    op.add_column('plot', sa.Column('finca', sa.String(), nullable=True))
    op.add_column('plot', sa.Column('sector', sa.String(), nullable=True))
    op.alter_column('task_list', 'task_list_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("nextval('task_list_task_list_id_seq'::regclass)"))
    op.alter_column('task_list', 'task_key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('task_list', 'task_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index('ix_task_list_task_list_id', table_name='task_list')
    op.create_index(op.f('ix_task_list_task_key'), 'task_list', ['task_key'], unique=True)
    op.alter_column('usuarios', 'nombre',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'nombre',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_task_list_task_key'), table_name='task_list')
    op.create_index('ix_task_list_task_list_id', 'task_list', ['task_list_id'], unique=False)
    op.alter_column('task_list', 'task_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('task_list', 'task_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('task_list', 'task_list_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("nextval('task_list_task_list_id_seq'::regclass)"))
    op.drop_column('plot', 'sector')
    op.drop_column('plot', 'finca')
    op.drop_constraint(None, 'operaciones', type_='foreignkey')
    op.create_foreign_key('operaciones_tipo_operacion_fkey', 'operaciones', 'task_list', ['tipo_operacion'], ['task_name'])
    # ### end Alembic commands ###
