"""Add sector_id to plot table

Revision ID: 6d1c2b1cd2fa
Revises: 7796a427ae0d
Create Date: 2025-09-04 14:55:23.028166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '6d1c2b1cd2fa'
down_revision: Union[str, None] = '7796a427ae0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
