"""Relaciones finca y sector- ULTIMISIMA

Revision ID: 876b3dde506b
Revises: d30e048d0998
Create Date: 2025-08-29 15:19:10.760103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '876b3dde506b'
down_revision: Union[str, None] = 'd30e048d0998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plot', sa.Column('sector_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'plot', 'sectores', ['sector_id'], ['id'])
    op.drop_column('plot', 'sector')
    op.drop_column('plot', 'finca')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plot', sa.Column('finca', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('plot', sa.Column('sector', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'plot', type_='foreignkey')
    op.drop_column('plot', 'sector_id')
    # ### end Alembic commands ###
