"""Sincronizar esquema con el estado actual de la base de datos

Revision ID: beda8f20f16c
Revises: c71d5aeaaec0
Create Date: 2025-08-29 12:16:18.813103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'beda8f20f16c'
down_revision: Union[str, None] = 'c71d5aeaaec0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #op.alter_column('task_list', 'task_list_id',
    #           existing_type=sa.INTEGER(),
    #           nullable=True)
    op.alter_column('task_list', 'task_key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_task_list_task_list_id', table_name='task_list')
    op.create_index(op.f('ix_task_list_task_key'), 'task_list', ['task_key'], unique=True)
    op.alter_column('usuarios', 'nombre',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'nombre',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_task_list_task_key'), table_name='task_list')
    op.create_index('ix_task_list_task_list_id', 'task_list', ['task_list_id'], unique=False)
    op.alter_column('task_list', 'task_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('task_list', 'task_list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
