"""Relaciones finca y sector- ULTIMA

Revision ID: d30e048d0998
Revises: 158a701b41b2
Create Date: 2025-08-29 15:18:05.245430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'd30e048d0998'
down_revision: Union[str, None] = '158a701b41b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plot', sa.Column('sector_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'plot', 'sectores', ['sector_id'], ['id'])
    op.drop_column('plot', 'finca')
    op.drop_column('plot', 'sector')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plot', sa.Column('sector', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('plot', sa.Column('finca', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'plot', type_='foreignkey')
    op.drop_column('plot', 'sector_id')
    # ### end Alembic commands ###
