"""IMAGENES

Revision ID: e1ce4d8d5848
Revises: 1ba2b4b86f08
Create Date: 2025-09-14 21:20:13.783003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'e1ce4d8d5848'
down_revision: Union[str, None] = '1ba2b4b86f08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_categoria_imagenes_id_categoria_img'), 'categoria_imagenes', ['id_categoria_img'], unique=False)
    op.alter_column('vitacora_campo', 'id_categoria_img',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('idx_vitacora_campo_categoria', table_name='vitacora_campo')
    op.drop_index('idx_vitacora_campo_fecha_captura', table_name='vitacora_campo')
    op.drop_index('idx_vitacora_campo_fecha_creacion', table_name='vitacora_campo')
    op.create_index(op.f('ix_vitacora_campo_id_vitacora'), 'vitacora_campo', ['id_vitacora'], unique=False)
    op.drop_constraint('vitacora_campo_id_categoria_img_fkey', 'vitacora_campo', type_='foreignkey')
    op.create_foreign_key(None, 'vitacora_campo', 'categoria_imagenes', ['id_categoria_img'], ['id_categoria_img'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vitacora_campo', type_='foreignkey')
    op.create_foreign_key('vitacora_campo_id_categoria_img_fkey', 'vitacora_campo', 'categoria_imagenes', ['id_categoria_img'], ['id_categoria_img'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_vitacora_campo_id_vitacora'), table_name='vitacora_campo')
    op.create_index('idx_vitacora_campo_fecha_creacion', 'vitacora_campo', ['fecha_creacion'], unique=False)
    op.create_index('idx_vitacora_campo_fecha_captura', 'vitacora_campo', ['fecha_captura'], unique=False)
    op.create_index('idx_vitacora_campo_categoria', 'vitacora_campo', ['id_categoria_img'], unique=False)
    op.alter_column('vitacora_campo', 'id_categoria_img',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_categoria_imagenes_id_categoria_img'), table_name='categoria_imagenes')
    # ### end Alembic commands ###
